name: Trivy_CI

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true

jobs:
  trivy:
    name: "Trivy Image Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ inputs.service-name }}
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/${{ inputs.service-name }}:${{ inputs.tag }}'
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: HIGH,CRITICAL